version: "3"
volumes:
  data:
    driver: local
services:
  pg09:
    #image: jonixis/postgres-madlib:latest
    image: madlib-a4a
    container_name: postgres-madlib
    ports:
      - "5439:5432"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
  pgrestDL05:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/dl05s_main
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_PORT=3105
  pgrestDL06:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - RACK_ENV=development
      - PGRST_DB_URI=postgres://postgres@localhost/dl06t_main
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_PORT=3106
