version: "3"
services:
  pgrestDL03:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    #ports:
    #  - "3103:3103"
    network_mode: host
    environment:
      - RACK_ENV=development
      - PGRST_DB_URI=postgres://postgres@localhost/dl03t_main
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api 
      - PGRST_SERVER_PORT=3103
  pgrestDL04:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    #ports:
    #  - "3104:3104"
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/dl04s_main
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_PORT=3104
  pgrestDL10:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    #ports:
    #  - "3110:3110"
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/dl10s_osmcod
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=public
      - PGRST_SERVER_PORT=3110
  co_ba:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    #ports:
    #  - "3001:3001"
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/co_ba
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=public
      - PGRST_SERVER_PORT=3001
  pgrestDL02:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    #ports:
    #  - "3102:3102"
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/dl02s_main
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_PORT=3102
