version: "3"
services:
  pgrestDL05:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - RACK_ENV=production
      - PGRST_DB_URI=postgres://postgres@localhost/dl05s_main
      - PGRST_DB_ANON_ROLE=webanon
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_HOST=localhost
      - PGRST_SERVER_PORT=3105
      - PGRST_OPENAPI_SERVER_PROXY_URI=https://api.afa.codes
  pgrestDL06:
    image: postgrest/postgrest:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - RACK_ENV=development
      - PGRST_DB_URI=postgres://postgres@localhost/dl06t_main
      - PGRST_DB_ANON_ROLE=webanon
      - PGRST_DB_SCHEMA=api
      - PGRST_SERVER_HOST=localhost
      - PGRST_SERVER_PORT=3106
      - PGRST_OPENAPI_SERVER_PROXY_URI=https://api.test.afa.codes
